name: default actions

on: [push, pull_request]

jobs:
  tests:
    name: run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: setup-go 1.14
        uses: ./
        with:
          go-version: 1.14

      - name: run all tests
        run: |
          go test -v ./...
