name: default actions

on: [push, pull_request]

jobs:
  test:
    name: run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Go 1.14
        uses: actions/setup-go@v2
        with:
          go-version: 1.14

      - name: run go test
        run: |
          cd ./application/
          go test -v ./...
